name: Build and Release Executables

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write


jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r software/QubeMonitorApp/requirements.txt
          pip install pyinstaller pillow

      - name: Build Windows executable
        shell: bash
        run: |
          cd software/QubeMonitorApp
          pyinstaller --onefile --windowed --name QubeMonitor --icon=dice_icon_160194.ico --add-data "dice_icon_160194.ico;." --hidden-import serial.tools.list_ports --hidden-import tkinter --hidden-import tkinter.ttk --hidden-import tkinter.messagebox --hidden-import tkinter.scrolledtext --hidden-import threading --hidden-import time qubeMonitor.py

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: QubeMonitor-Windows
          path: software/QubeMonitorApp/dist/QubeMonitor.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r software/QubeMonitorApp/requirements.txt
          pip install pyinstaller pillow

      - name: Build macOS executable
        run: |
          cd software/QubeMonitorApp
          pyinstaller --onedir --windowed --name QubeMonitor-Mac --icon=dice_icon_160194.ico --add-data "dice_icon_160194.ico:." --hidden-import serial.tools.list_ports --hidden-import tkinter --hidden-import tkinter.ttk --hidden-import tkinter.messagebox --hidden-import tkinter.scrolledtext --hidden-import threading --hidden-import time qubeMonitor.py

      - name: Archive macOS app bundle
        run: |
          cd software/QubeMonitorApp/dist
          zip -r QubeMonitor-Mac.zip QubeMonitor-Mac.app

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: QubeMonitor-Mac
          path: software/QubeMonitorApp/dist/QubeMonitor-Mac.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r software/QubeMonitorApp/requirements.txt
          pip install pyinstaller pillow

      - name: Build Linux executable
        run: |
          cd software/QubeMonitorApp
          pyinstaller --onefile --windowed --name QubeMonitor-Linux --icon=dice_icon_160194.ico --add-data "dice_icon_160194.ico:." --hidden-import serial.tools.list_ports --hidden-import tkinter --hidden-import tkinter.ttk --hidden-import tkinter.messagebox --hidden-import tkinter.scrolledtext --hidden-import threading --hidden-import time qubeMonitor.py

      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: QubeMonitor-Linux
          path: software/QubeMonitorApp/dist/QubeMonitor-Linux

  release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate tag name
        run: echo "TAG_NAME=$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        run: |
          gh release create "$TAG_NAME" \
            "artifacts/QubeMonitor-Windows/QubeMonitor.exe" \
            "artifacts/QubeMonitor-Mac/QubeMonitor-Mac.zip" \
            "artifacts/QubeMonitor-Linux/QubeMonitor-Linux" \
            --title "Release $TAG_NAME" \
            --notes "Automated release of QubeMonitor at $TAG_NAME."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
