name: Build and Release Executables

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write


jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r software/LerarenApp/requirements.txt
          pip install pyinstaller

      - name: Build Windows executable
        shell: bash
        run: |
          cd software/LerarenApp
          pyinstaller --onefile --windowed \
            --icon=dice_icon_160194.ico \
            --name=LerarenApp-Windows lerarenApp.py

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: LerarenApp-Windows
          path: software/LerarenApp/dist/LerarenApp-Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r software/LerarenApp/requirements.txt
          pip install pyinstaller

      - name: Build macOS executable
        run: |
          cd software/LerarenApp
          pyinstaller --onefile --windowed \
            --name=LerarenApp-Mac lerarenApp.py

      - name: Archive macOS app bundle
        run: |
          cd software/LerarenApp/dist
          zip -r LerarenApp-Mac.zip LerarenApp-Mac.app

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: LerarenApp-Mac
          path: software/LerarenApp/dist/LerarenApp-Mac.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r software/LerarenApp/requirements.txt
          pip install pyinstaller

      - name: Build Linux executable
        run: |
          cd software/LerarenApp
          pyinstaller --onefile --windowed \
            --name=LerarenApp-Linux lerarenApp.py

      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: LerarenApp-Linux
          path: software/LerarenApp/dist/LerarenApp-Linux

  release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate tag name
        run: echo "TAG_NAME=$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        run: |
          gh release create "$TAG_NAME" \
            "artifacts/LerarenApp-Windows/LerarenApp-Windows.exe" \
            "artifacts/LerarenApp-Mac/LerarenApp-Mac.zip" \
            "artifacts/LerarenApp-Linux/LerarenApp-Linux" \
            --title "Release $TAG_NAME" \
            --notes "Automated release of LerarenApp at $TAG_NAME."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
